// 各課的「學習重點」說明(2026-10-06):自由練習的單元清單只有課名,孩子想練「現在完成式」卻不知道在哪一課。
// 英文:每課主要文法,每一項都有該課康軒習作的原文依據(逐課對照表 data/lesson-notes-audit.md;
// 原始比對 data/rerender/notes-audit/),習作找不到練習的文法不寫。
// 國文:作者｜文體｜重點,每一項都有該課康軒教材(題庫題目與答案、習作、補救教學卷、課本應用練習)的原文依據;
// 找不到明文的作者/文體不寫(對照表 data/lesson-notes-audit.md)。
// key =「冊別|單元名稱」,對應題庫 volume 與 topic 欄位(例「第 5 冊|L1_Have You Ever Tried These Dishes」)。

const NOTES: Record<string, Record<string, string>> = {
  english: {
    "第 1 冊|Get Ready": "大小寫字母與句子書寫格式、人稱代名詞主格與所有格",
    "第 1 冊|L1_Who's That Young Man": "be 動詞(am / is / are)、Who 問句、不定冠詞 a / an",
    "第 1 冊|L2_What Are These": "this / that / these / those、名詞單複數、be 動詞問句",
    "第 1 冊|L3_Let's Get Some Ideas from RoomGPT": "祈使句、Let's…、地方介系詞、Where 問句",
    "第 1 冊|L4_I Can Listen to Their Songs Again and Again": "助動詞 can(肯定、否定、問句)、祈使句(Don't…)",
    "第 1 冊|L5_What Are You Doing": "現在進行式、What time / What day 問句、時間介系詞",
    "第 1 冊|L6_Are There Any Shelves Outside the Door": "There is / There are、some / any",
    "第 1 冊|Review 1": "複習:be 動詞、疑問詞(Who / Where / How old)、所有格",
    "第 1 冊|Review 2": "複習:There is / are、地方介系詞、these / Where 問句",
    "第 1 冊|Review 3": "複習:現在進行式、What time / What day 問句、祈使句",
    "第 2 冊|L1_Alan Plays Basketball Every Day": "現在簡單式(第三人稱單數動詞)、Do / Does 問句",
    "第 2 冊|L2_How Often Do You Clean Your Room": "頻率副詞、How often 問句(once / twice / … times)",
    "第 2 冊|L3_What's the Date Today": "日期與序數、When / Whose 問句、所有格代名詞(mine)、日期前用 on",
    "第 2 冊|L4_How Much Cake Do You Want": "可數與不可數名詞、How many / How much、數量詞、Which 問句",
    "第 2 冊|L5_You Helped Me a Lot": "過去簡單式(be 動詞與一般動詞)、過去時間副詞",
    "第 2 冊|L6_They Got Lots of People Together and Cleaned Up Bali's Beaches": "不規則動詞過去式、過去式問句(Did…? / What did…?)",
    "第 3 冊|L1_It Rained a Lot Yesterday": "天氣的問答、過去式(含 There + be 過去式)",
    "第 3 冊|L2_Why Didn't You See a Doctor": "Why 問句、because / so、授與動詞(give / buy + 人 + 物)",
    "第 3 冊|L3_Tina and Billy Were Looking for Water": "過去進行式、時間連接詞(when / before / after)",
    "第 3 冊|L4_I Want to Be a YouTuber": "不定詞(to V)、動名詞(V-ing)、It is…to V(虛主詞)",
    "第 3 冊|L5_How Long Will We Stay in Bangkok": "未來式(will / be going to)、spend / take / cost、How long 問句",
    "第 3 冊|L6_How Do We Get to Joe's House": "問路與交通方式、take(搭乘/花費時間)",
    "第 4 冊|L1_The Coat Is Lighter Than the Jacket": "形容詞比較級、代名詞 one / ones",
    "第 4 冊|L2_He's the Best Singer in the World": "形容詞最高級、used to(過去習慣)",
    "第 4 冊|L2_This Must Be the Oldest Machine in Your Store": "形容詞最高級",
    "第 4 冊|L3_Our Food Smells Good": "連綴動詞 + 形容詞(look / smell / taste)、使役動詞(make / have / let)",
    "第 4 冊|L4_Let's Set Up Camp Quickly": "情狀副詞、副詞比較級與最高級",
    "第 4 冊|L5_I Felt the Floor Shaking": "感官動詞 + V / V-ing、反身代名詞、not only…but also",
    "第 4 冊|L5_I Felt the Ground Shaking When the Earthquake Hit": "感官動詞(see / hear / feel + V / V-ing)、反身代名詞",
    "第 4 冊|L6_If We Don't Act Now, There Will Be More Plastic in the Ocean": "if 條件句、although / though、不定代名詞(both / all / one of)",
    "第 5 冊|L1_Have You Ever Tried These Dishes": "現在完成式(have / has + p.p.)、ever / already / yet、since / for",
    "第 5 冊|L2_Are You Interested in Trying Food Delivery Apps": "分詞形容詞(interested / interesting)、that 名詞子句",
    "第 5 冊|L3_Movies Are Made to Help People Dream": "被動語態(be + p.p.)、附加問句",
    "第 5 冊|L4_Do You Know What These Words Mean": "間接問句(疑問詞名詞子句)、if / whether 名詞子句、疑問詞 + to V",
    "第 5 冊|L5_The Amazing Candy That Cleans Your Teeth": "關係代名詞 that / which / who(主格)",
    "第 5 冊|L6_Are You One of the Customers Who Businesses Trick": "關係代名詞受格(who / which / that,可省略)、whose",
    "第 6 冊|L1_Sharing News Is OK as Long as You Check It First": "副詞子句連接詞(as soon as / as long as / while / until)",
    "第 6 冊|L2_Jokes Don't Have to Be Mean, and Neither Do the People Who Tell Them": "附和句(so / too / either / neither)、either…or / neither…nor、too…to / so…that",
    "第 6 冊|L3_The Age of AI Has Begun": "名詞子句與間接問句(that / if / whether / 疑問詞)、to V 與 V-ing",
    "第 6 冊|L4_Looking Back on the Good Old Days": "使役動詞(make / have / let)、感官動詞(hear + 受詞 + V)、連綴動詞(look / look like)",
  },
  chinese: {
    "第 1 冊|下雨天，真好": "記敘文｜雨天勾起童年回憶、懷念母親",
    "第 1 冊|自學一 善用時間的方法": "李偉文｜要節省工作、專注真正重要的事",
    "第 1 冊|那默默的一群": "張騰蛟｜記敘文｜讚美默默付出的清道婦、譬喻、誇飾",
    "第 1 冊|差不多先生傳": "胡適｜寓言(傳記手法)｜諷刺國人做事馬虎、不認真；倒反",
    "第 1 冊|語文天地二  閱讀策略與資料檢索": "語文常識｜閱讀策略(擷取訊息、摘要重點)與資料檢索",
    "第 2 冊|今夜看螢去": "散文｜螢火蟲之美與古典詩文中的螢、感嘆流螢日稀",
    "第 2 冊|自學一 東風吹馬耳": "說明文｜從動物聽覺科學檢視成語「東風吹馬耳」",
    "第 2 冊|近體詩選": "王維、李白、杜甫｜近體詩｜山居秋暝、早發白帝城、聞官軍收河南河北",
    "第 2 冊|記承天夜遊": "蘇軾｜記敘兼抒情｜月夜賞景，貶謫中的閒適曠達",
    "第 2 冊|語文天地二 字體演變與書法欣賞": "語文常識｜漢字字體演變與書法欣賞",
    "第 3 冊|土芭樂的生存之道": "劉克襄｜散文｜從土芭樂體悟生存之道、摹寫",
    "第 3 冊|五柳先生傳": "陶淵明｜傳記｜自況的五柳先生、安貧樂道不慕榮利",
    "第 3 冊|自學一 世說新語選": "劉義慶｜《世說新語》選讀(華王優劣等)",
    "第 3 冊|我在圖書館的一天": "鍾文音｜記敘文｜圖書館的閱讀時光與自然景致；轉化",
    "第 3 冊|愛蓮說": "周敦頤｜論說文｜詠物言志、以蓮喻君子、以菊與牡丹襯托蓮",
    "第 4 冊|一棵開花的樹": "新詩｜化身開花的樹等待愛人、誇飾",
    "第 4 冊|自學二 拍痰": "記敘文｜病房中的拍痰與外籍看護，關懷照護者的處境",
    "第 4 冊|陋室銘": "劉禹錫｜銘｜陋室不陋，安貧樂道、德行高潔；借代",
    "第 4 冊|情緒是生命的指引": "留佩萱｜說理文｜情緒沒有好壞，正視並感受情緒",
    "第 4 冊|語文天地二 題辭、柬帖": "語文常識｜題辭與柬帖的用法",
    "第 5 冊|人間好時節": "張曼娟｜記敘、議論兼抒情｜從四季詩詞體會人生，心無罣礙便是好時節；引用",
    "第 5 冊|自學二 大明湖": "劉鶚《老殘遊記》｜寫景｜大明湖、千佛山倒影之景",
    "第 5 冊|喂——出來！": "科幻小說｜深不見底的洞、諷刺人類丟棄問題",
    "第 5 冊|與宋元思書": "吳均｜書信(駢文)｜富春江奇山異水",
    "第 5 冊|獵人": "瓦歷斯．諾幹｜記敘文｜泰雅族成年禮狩獵，傳承原住民文化；譬喻",
    "第 6 冊|后羿射月": "劇本｜以舞臺劇呈現后羿與嫦娥的故事",
    "第 6 冊|自學二 錢是省出來的": "記敘文｜阿公與家人的節儉家風，坦然接受節儉習性",
    "第 6 冊|憶高畑勳：螢火蟲之墓": "藍祖蔚｜電影評論｜追憶高畑勳動畫的人道精神、反戰",
    "第 1 冊|生之歌選": "杏林子｜短文｜〈一顆珍珠〉〈手的故事〉、苦難中體悟生命、映襯",
    "第 1 冊|自學二 拄枴杖的小男孩": "記敘｜身障孩童馬托獲得友善對待、反思臺灣無障礙環境",
    "第 1 冊|兒時記趣": "沈復｜記敘文｜童年物外之趣、細膩觀察與想像",
    "第 1 冊|紙船印象": "洪醒夫｜童年摺紙船，感念母愛與堅強的期許",
    "第 1 冊|論語選": "為學的態度與方法、見賢思齊、推己及人的恕道",
    "第 2 冊|另一個春天": "褚士瑩｜記敘文｜希臘旅途中與東德老太太的情誼、對生命的熱情與活力",
    "第 2 冊|自學二 賣油翁": "歐陽脩｜賣油翁與陳康肅的對比、熟能生巧",
    "第 2 冊|背影": "朱自清｜車站送別的背影，體會深沉父愛；倒反",
    "第 2 冊|傘": "蓉子｜詠物詩｜以譬喻描寫傘的形象，心境自主不受外物影響",
    "第 2 冊|聲音鐘": "陳黎｜小販叫賣聲如鐘報時、城市生活的旋律、轉化",
    "第 3 冊|小詩選": "白靈等｜風箏(與天空拔河的意志)、跳水；轉化、象徵",
    "第 3 冊|古體詩選": "白居易／古詩十九首｜古體詩｜慈烏夜啼(孝親反哺)、庭中有奇樹(思念)",
    "第 3 冊|自學二 定伯賣鬼": "宋定伯機智捉鬼賣鬼、人鬼對比",
    "第 3 冊|拆牆": "跨文化鄰居蓋茲與含月的愛情、文化隔閡的建立與破除、象徵",
    "第 3 冊|語文天地一 語法（上）——詞類介紹": "語文常識｜語法：詞類(實詞與虛詞)介紹",
    "第 4 冊|成功是失敗之母": "黃永武｜議論文｜成功後驕傲自滿易致敗亡、須保持警醒、引用史例",
    "第 4 冊|自學三 空城計": "羅貫中《三國演義》｜諸葛亮空城計退司馬懿、烘托",
    "第 4 冊|迷途羔羊——弗氏海豚": "廖鴻基｜記敘｜觀察弗氏海豚、反思人類才是迷途羔羊",
    "第 4 冊|項鍊": "莫泊桑｜小說｜虛榮的代價、出人意料的結局",
    "第 4 冊|樂府詩選——木蘭詩": "北朝民歌｜樂府詩｜木蘭代父從軍；頂真",
    "第 5 冊|生於憂患死於安樂": "孟子｜憂患使人成長、安樂使人敗亡、排比與映襯",
    "第 5 冊|自學三 無關歲月": "記敘｜遷臺家庭的過年習俗，體會父母對生命的慎重",
    "第 5 冊|畫說湖心亭看雪": "劉墉／張岱｜賞析湖心亭看雪的煉字、造景與著色",
    "第 5 冊|語文天地 對聯": "語文常識｜對聯的格式與應用",
    "第 6 冊|二十年後": "歐．亨利｜短篇小說｜二十年之約、伏筆與出人意料的結局",
    "第 6 冊|曲選": "馬致遠、白樸｜散曲(小令)｜天淨沙·秋思、沉醉東風·漁父詞",
    "第 6 冊|自學三 賀伯吹來的教導": "賀伯颱風、部落集體重建、尊重自然",
    "第 1 冊|吃冰的滋味": "古蒙仁｜童年吃冰回憶，對照今昔變遷；誇飾、摹寫",
    "第 1 冊|自學三 曹操掉下去了": "剪黏藝術與廟宇修繕",
    "第 1 冊|夏夜": "楊喚｜新詩｜夏夜寧靜之美、轉化(擬人)",
    "第 1 冊|語文天地一  標點符號使用法": "語文常識｜標點符號的用法",
    "第 1 冊|鬧元宵": "元宵節燈籠、湯圓、舞龍的童年記憶；摹寫",
    "第 2 冊|四種讀書的方法": "傅佩榮｜精讀、略讀、重讀、默讀四種讀書方法",
    "第 2 冊|自學三 再見，西莎": "偶遇被棄的流浪狗，關懷動物",
    "第 2 冊|音樂家與職籃巨星": "論說文｜魯賓斯坦與喬丹的成功、勤能補拙、舉例論證",
    "第 2 冊|語文天地一 文字構造介紹": "語文常識｜文字構造：象形、指事、會意、形聲",
    "第 2 冊|謝天": "陳之藩｜謝天之真諦：得之於人者太多，感恩、映襯",
    "第 3 冊|不要放棄你的夢想": "羅蘭｜堅持夢想、對自己負責，不做鄉愿",
    "第 3 冊|田園之秋選": "陳冠學｜描寫西北雨的變化；譬喻",
    "第 3 冊|自學三 買春聯": "買手寫春聯，憶眷村家人與練字往事",
    "第 3 冊|鳥": "梁實秋｜愛鳥的聲音與形體，同情籠中鳥的苦悶",
    "第 3 冊|語文天地二 語法（下）——句型介紹": "語文常識｜句型：敘事句、有無句、表態句、判斷句",
    "第 4 冊|自學一 運動家的風度": "議論文｜運動家應有的風度：服輸、超越勝敗",
    "第 4 冊|我所知道的康橋": "徐志摩｜康橋風光與心靈感受、譬喻",
    "第 4 冊|張釋之執法": "司馬遷《史記》｜記敘文(文言史傳)｜張釋之守法不阿、執法公正",
    "第 4 冊|語文天地一 書信、便條": "語文常識｜書信與便條的格式、用語",
    "第 4 冊|罐頭由來": "說明文｜罐頭的發明與改良歷史",
    "第 5 冊|自學一 養成新聞判讀力，迎向更美好的生活": "以關窗簡訊為例、判讀資訊真偽",
    "第 5 冊|清心苦味": "韓良露｜由苦味體悟人生、苦可清心",
    "第 5 冊|詞選": "李清照、辛棄疾｜詞｜〈如夢令〉惜花傷春；〈南鄉子〉藉古諷今",
    "第 5 冊|戲李白": "余光中｜新詩｜以戲謔筆調推崇李白詩才；化用李白、蘇軾詩句",
    "第 6 冊|火車與熱氣球": "以旅行比喻人生求道、引用",
    "第 6 冊|自學一 聊齋志異選——種梨": "道士種梨，諷刺吝嗇鄉人",
    "第 6 冊|臺灣竹枝詞選": "郁永河｜竹枝詞｜〈蔗田〉〈鹿耳門〉、臺灣風土",
  },
};

/** 取得某課的學習重點;沒有資料回傳空字串 */
export function lessonNote(subject: string, volume: string | null | undefined, topic: string): string {
  return NOTES[subject]?.[`${volume ?? ""}|${topic}`] ?? "";
}

/** 這一科有沒有整理學習重點(有才顯示搜尋框) */
export const hasLessonNotes = (subject: string) => Object.keys(NOTES[subject] ?? {}).length > 0;
